name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-nginx:latest

      # Step 4: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop old container if running
            docker ps -q --filter "name=final-devops-project-fullstack-app" | xargs -r docker stop | xargs -r docker rm

            # Pull latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-nginx:latest

            # Run container with correct port mapping
            docker run -d \
              --name final-devops-project-fullstack-app \
              -p 8081:80 \
              -p 8080:8080 \
              --restart always \
              ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-nginx:latest
